### ISSUE TITLE
"Check" menu entry.

### ISSUE THREAD

**Issue by vi** [integer32llc/rust-playground#334] opened 2018-05-23 16:42 UTC
Sometimes running the program is a waste of time and resources.

Maybe there should be the "Check" menu entry?

**Comment by shepmaster** [comment] 2018-08-09 22:28
Duplicate of #131

I'd love it if you could add on #131 why you'd want to do this as opposed to just `cargo build`.

**Closed by shepmaster** 2018-08-09 22:28 UTC
