### ISSUE TITLE
"Permalink to the playground" redirects to non-permalink url

### ISSUE THREAD

**Issue by WaffleLapkin** [integer32llc/rust-playground#887] opened 2023-01-20 17:34 UTC
When I click on "Permalink to the playground" the browser URL first becomes one with `&gist=...` i.e. a permalink one, but then after a split second playground redirects me to the non-`&gist=...`, non-permanent URL.

This is very confusing, as the "usual" way to share code does not work anymore:
1. Write the code
2. Click "Permalink to the playground"
3. Copy the browser URL (<-- does not work anymore)

This has caused me (and others) to post links to playground like "https://play.rust-lang.org/?version=stable&mode=debug&edition=2021" which do not point to any particular code.

**Comment by c-git** [comment] 2023-01-20 18:10
The button next to  "Permalink to the playground" (highlighted in the image below) seems to work in the mean while.

![image](https://user-images.githubusercontent.com/43485962/213772007-4958d2ff-8d26-4ffe-b7f0-d3240e9eade0.png)

PS. I noticed someone created an issue regarding this recently as well https://github.com/integer32llc/rust-playground/issues/884#issue-1548468210

**Comment by shepmaster** [comment] 2023-01-20 18:20
Duplicate of #884

**Closed by shepmaster** 2023-01-20 18:20 UTC
