### ISSUE TITLE
Feature Request: Automatically switch to nightly compiler if `#![feature(..)]` is encountered.

### ISSUE THREAD

**Issue by drXor** [integer32llc/rust-playground#378] opened 2018-08-15 22:25 UTC
I use the playground almost exclusively to test pathological examples, a lot of which involve at least one feature gate. It's a bit of a papercut to write something with a pile of pragmas and get hit with the "no feature gates on stable" error, and then have to manually switch over to nightly.

I think it's reasonable to just search for uses of `#![feature]` pre-macro expansion- that covers pretty much all reasonable use-cases.

**Comment by shepmaster** [comment] 2018-08-16 01:12
Duplicate of #317 & #314

**Closed by shepmaster** 2018-08-16 01:12 UTC
