### ISSUE TITLE
Linking error

### ISSUE THREAD

**Issue by KaiserKarel** [integer32llc/rust-playground#670] opened 2021-01-12 09:55 UTC
The following https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=fb451cb4c59d849375d6d4de02ab1bd8 produces a linking error.

```
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-Wl,--eh-frame-hdr" "-L" "/playground/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "/playground/target/debug/deps/playground-bb452379b09dd6b8.playground.4r8kn1pw-cgu.0.rcgu.o" "-o" "/playground/target/debug/deps/playground-bb452379b09dd6b8" "/playground/target/debug/deps/playground-bb452379b09dd6b8.300xwxforejvn119.rcgu.o" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro" "-Wl,-znow" "-nodefaultlibs" "-L" "/playground/target/debug/deps" "-L" "/playground/target/debug/build/backtrace-sys-ecab8ec51b341a79/out" "-L" "/playground/target/debug/build/libsqlite3-sys-bfc805e5ad2ca8d0/out" "-L" "/playground/target/debug/build/ring-c22b6d33a599ddae/out" "-L" "/playground/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/playground/target/debug/deps/libtokio-e04df457e80938f8.rlib" "/playground/target/debug/deps/libbytes-f83af01ab5a4c8a1.rlib" "/playground/target/debug/deps/libmio-092c0f5158ef5d02.rlib" "/playground/target/debug/deps/libparking_lot-e0e73211d3f6cd8b.rlib" "/playground/target/debug/deps/libparking_lot_core-2010bd407414fdfd.rlib" "/playground/target/debug/deps/liblock_api-4cb2cc04d0a6a2da.rlib" "/playground/target/debug/deps/libscopeguard-a1229ee08a255f9f.rlib" "/playground/target/debug/deps/libinstant-a99ec039e5d0e43b.rlib" "/playground/target/debug/deps/libreqwest-7cd77ddb25fd13e4.rlib" "/playground/target/debug/deps/libcookie_store-868ba49a6f679fa2.rlib" "/playground/target/debug/deps/libpublicsuffix-d2d94016faca66d9.rlib" "/playground/target/debug/deps/libregex-72cd68e704cd3488.rlib" "/playground/target/debug/deps/libthread_local-51e5e712f01f8854.rlib" "/playground/target/debug/deps/libregex_syntax-79540a020ca7cb1e.rlib" "/playground/target/debug/deps/libaho_corasick-ec77dcbba7db0b2f.rlib" "/playground/target/debug/deps/liberror_chain-469bbe93f93693f7.rlib" "/playground/target/debug/deps/libbacktrace-34a73a02bd41eb7a.rlib" "/playground/target/debug/deps/libaddr2line-2e2c851cba49ddd8.rlib" "/playground/target/debug/deps/libsmallvec-1d36d7be2afeb310.rlib" "/playground/target/debug/deps/libobject-5f0495e2344022e1.rlib" "/playground/target/debug/deps/libflate2-8bea33f0df7b5ad2.rlib" "/playground/target/debug/deps/libminiz_oxide-7e3fd996661bdc9d.rlib" "/playground/target/debug/deps/libadler-ec84003b19df3f64.rlib" "/playground/target/debug/deps/libcrc32fast-07a09453e431a3ed.rlib" "/playground/target/debug/deps/libwasmparser-4c12f2435dc5be79.rlib" "/playground/target/debug/deps/libgimli-1325172d63848d83.rlib" "/playground/target/debug/deps/libstable_deref_trait-a773e105e2a3095f.rlib" "/playground/target/debug/deps/libfallible_iterator-2219986f9926d6bc.rlib" "/playground/target/debug/deps/libcpp_demangle-aff6c86b2f91fb0a.rlib" "/playground/target/debug/deps/librustc_demangle-457d5f338b86b6e2.rlib" "/playground/target/debug/deps/libcookie-521f422a63e7dd97.rlib" "/playground/target/debug/deps/libtime-005cee3806f30a1b.rlib" "/playground/target/debug/deps/libtime_macros-811d50653d41675f.rlib" "/playground/target/debug/deps/libstandback-940905eb744a2628.rlib" "/playground/target/debug/deps/libhyper_tls-9abb84cd14392631.rlib" "/playground/target/debug/deps/libipnet-dd4017042ce48c65.rlib" "/playground/target/debug/deps/libtokio_tls-32f9682d58b5ff55.rlib" "/playground/target/debug/deps/libserde_urlencoded-2fec6cddb574588a.rlib" "/playground/target/debug/deps/libencoding_rs-8e15fbe16dbf91ee.rlib" "/playground/target/debug/deps/libserde_json-2c779f6c287446f5.rlib" "/playground/target/debug/deps/libryu-6241efeb30b80bba.rlib" "/playground/target/debug/deps/libbase64-ec253169f6bc0871.rlib" "/playground/target/debug/deps/libmime_guess-1df4d5f3a38fe1a0.rlib" "/playground/target/debug/deps/libunicase-61f3bfb40d6e733e.rlib" "/playground/target/debug/deps/libmime-0faf3a3ffb52769e.rlib" "/playground/target/debug/deps/libnative_tls-3ce88d91a96280d8.rlib" "/playground/target/debug/deps/libopenssl_probe-76281ad958c02c30.rlib" "/playground/target/debug/deps/libopenssl-2fe96d9893c9816f.rlib" "/playground/target/debug/deps/libopenssl_sys-9166d34fa72d68d9.rlib" "/playground/target/debug/deps/libforeign_types-b3c3fd39daf721e3.rlib" "/playground/target/debug/deps/libforeign_types_shared-f86773b0d865590d.rlib" "/playground/target/debug/deps/libbitflags-51f38ea8417d9081.rlib" "/playground/target/debug/deps/libhyper-ad57c902eebee5ea.rlib" "/playground/target/debug/deps/libhttparse-a0a2a407c364c7be.rlib" "/playground/target/debug/deps/libwant-e58e297837fb589f.rlib" "/playground/target/debug/deps/libtry_lock-5ed03396bb7d201d.rlib" "/playground/target/debug/deps/libh2-4d1de4ac2eb78ac6.rlib" "/playground/target/debug/deps/libtracing_futures-82ac15407db18e8d.rlib" "/playground/target/debug/deps/libpin_project-b54fdd7befaa0985.rlib" "/playground/target/debug/deps/libindexmap-3a036aa6d3940108.rlib" "/playground/target/debug/deps/libhashbrown-58ab26f3a2de3ad4.rlib" "/playground/target/debug/deps/libahash-06906e06abe77609.rlib" "/playground/target/debug/deps/libconst_random-862ea7b7fe6db970.rlib" "/playground/target/debug/deps/libtokio_util-605db94e40765f8e.rlib" "/playground/target/debug/deps/libhttpdate-a06b41d51c45beae.rlib" "/playground/target/debug/deps/libsocket2-8bf9b42a95d3d9b8.rlib" "/playground/target/debug/deps/libtower_service-d4feaebc6062529b.rlib" "/playground/target/debug/deps/libtracing-23af56629998ad80.rlib" "/playground/target/debug/deps/libtracing_core-44fe9f3d7bb46bb0.rlib" "/playground/target/debug/deps/libcfg_if-eed80f717dffdd66.rlib" "/playground/target/debug/deps/libtokio-b4fd8db362ec840f.rlib" "/playground/target/debug/deps/libsignal_hook_registry-b992b3a532d90e0f.rlib" "/playground/target/debug/deps/libnum_cpus-5b00dd19e59c044f.rlib" "/playground/target/debug/deps/libmio_uds-c355cb856c6f741a.rlib" "/playground/target/debug/deps/libmio-894665e91a181d95.rlib" "/playground/target/debug/deps/libnet2-9e41164d0047efb8.rlib" "/playground/target/debug/deps/libpin_project_lite-ce9ab2dfad85a49c.rlib" "/playground/target/debug/deps/libpin_project_lite-d438d5e764cb1c79.rlib" "/playground/target/debug/deps/libhttp_body-73667bc9e7c7864a.rlib" "/playground/target/debug/deps/libfutures_util-c7e0a8c2d4952879.rlib" "/playground/target/debug/deps/libmemchr-08da6318bbfcbea1.rlib" "/playground/target/debug/deps/libtokio_io-940364b9dbfcddfa.rlib" "/playground/target/debug/deps/libbytes-024b18310430d579.rlib" "/playground/target/debug/deps/libiovec-5e97a8e43e4b88d0.rlib" "/playground/target/debug/deps/liblibc-2a9d8bf62d056a2d.rlib" "/playground/target/debug/deps/libbyteorder-52e2d5591ba84a9d.rlib" "/playground/target/debug/deps/liblog-859fe90769a12897.rlib" "/playground/target/debug/deps/libcfg_if-01d225180328f085.rlib" "/playground/target/debug/deps/libfutures-5555c67c31c76b00.rlib" "/playground/target/debug/deps/libfutures_io-862821a2949711f0.rlib" "/playground/target/debug/deps/libslab-31b95f3d8bfe0bb8.rlib" "/playground/target/debug/deps/libfutures_channel-5d180f13ac8262e3.rlib" "/playground/target/debug/deps/libpin_project-c38ebb2cbeac3f64.rlib" "/playground/target/debug/deps/libfutures_sink-4752ddeaba23311f.rlib" "/playground/target/debug/deps/libfutures_task-90a2d1c9fda9650c.rlib" "/playground/target/debug/deps/libonce_cell-57fc7c67e92d5296.rlib" "/playground/target/debug/deps/libpin_utils-46f7bcd69e2969ea.rlib" "/playground/target/debug/deps/libfutures_core-1db61a7ced37099d.rlib" "/playground/target/debug/deps/liblazy_static-8cdb4e4e1fd0bb3a.rlib" "/playground/target/debug/deps/liburl-451cbe37d0c12260.rlib" "/playground/target/debug/deps/libidna-c6f870717a21d7b5.rlib" "/playground/target/debug/deps/libunicode_normalization-8f5f38881a2aea98.rlib" "/playground/target/debug/deps/libtinyvec-39b31b01ee9d2510.rlib" "/playground/target/debug/deps/libtinyvec_macros-c1d70a0a12e04ff7.rlib" "/playground/target/debug/deps/libserde-e0a6de3f257b1ba1.rlib" "/playground/target/debug/deps/libunicode_bidi-c97262f58f466cb6.rlib" "/playground/target/debug/deps/libform_urlencoded-1adc392415591539.rlib" "/playground/target/debug/deps/libpercent_encoding-9dafc0d6acd30ea7.rlib" "/playground/target/debug/deps/libmatches-8f4a735a670563b5.rlib" "/playground/target/debug/deps/libhttp-2dc9b137ba41985a.rlib" "/playground/target/debug/deps/libitoa-124d6e6daa08c024.rlib" "/playground/target/debug/deps/libbytes-71368cd15bc811fb.rlib" "/playground/target/debug/deps/libfnv-4a8975a6eff58ccd.rlib" "-Wl,--start-group" "/playground/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-e12de7683a34c500.rlib" "/playground/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-446a53c2e468675f.rlib" "/playground/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libminiz_oxide-86fef9fb252a2d33.rlib" "/playground/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libadler-3bed9bfd30304751.rlib" "/playground/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libobject-0e38eeb474a7b386.rlib" "/playground/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libaddr2line-a846ed547b824740.rlib" "/playground/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgimli-c9540f0a4fb9265d.rlib" "/playground/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_demangle-7d2ca66c92c356eb.rlib" "/playground/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libhashbrown-147e2c808f949493.rlib" "/playground/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_alloc-bd2a4369506670e9.rlib" "/playground/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-74bfdd0ce7d0ed48.rlib" "/playground/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcfg_if-6777f47f1c491841.rlib" "/playground/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-b104f1790174f2be.rlib" "/playground/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-db37898996f45c13.rlib" "/playground/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_core-25b7435131fc4938.rlib" "/playground/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-9d4b6f3c097e876e.rlib" "-Wl,--end-group" "/playground/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-3f953ad652ab829a.rlib" "-Wl,-Bdynamic" "-lssl" "-lcrypto" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc"
  = note: collect2: fatal error: ld terminated with signal 9 [Killed]
          compilation terminated
```

**Comment by shepmaster** [comment] 2021-01-12 12:38
You didn’t provide a valid link with source code.

**Comment by KaiserKarel** [comment] 2021-01-12 13:05
My bad! fixed it

**Comment by shepmaster** [comment] 2021-01-12 13:44
Duplicate of #608

**Closed by shepmaster** 2021-01-12 13:44 UTC
