### ISSUE TITLE
Suggestion: Add a reset button

### ISSUE THREAD

**Issue by Wilfred** [integer32llc/rust-playground#598] opened 2020-05-05 20:30 UTC
Preserving the state in the Rust playground is often helpful. Sometimes, I want a fresh hello world program I can edit though.

Would it be possible to add a reset button? I think this would be particularly useful for newcomers, who are unfamiliar with basic Rust syntax.

I can't see any way of doing this today, except opening the playground in an incognito browser.

**Comment by Wilfred** [comment] 2020-05-05 22:42
This would probably help with #595.

**Comment by shepmaster** [comment] 2020-05-06 01:30
Duplicate of #323

**Closed by shepmaster** 2020-05-06 01:30 UTC
