### ISSUE TITLE
Feature Request: Cargo expand

### ISSUE THREAD

**Issue by elichai** [integer32llc/rust-playground#551] opened 2019-12-12 10:38 UTC
Hi, 
I think  having the ability to run https://github.com/dtolnay/cargo-expand on the code there and see the result (replace the code with the result) will be quite helpful.

Thanks!

**Comment by shepmaster** [comment] 2019-12-13 15:37
Duplicate of #158

**Closed by shepmaster** 2019-12-13 15:37 UTC
