### ISSUE TITLE
No `rayon` crate in the playground

### ISSUE THREAD

**Issue by matklad** [integer32llc/rust-playground#113] opened 2017-03-13 21:08 UTC
Hi! 

It seems like the `rayon` crate is missing: http://play.integer32.com/?gist=04382a80d3f1f36a60a9a4933d382d92&version=stable

I think it should be included, it's one of the nicest crates to demonstrate the power of Rust :)

**Comment by shepmaster** [comment] 2017-03-14 02:26
Sorry! We strive to have simple heuristics to decide which crates are present. The current heuristic is the top 100 crates by all-time downloads. We've also toyed around with the idea of having "sponsored crates", where someone contributes money towards server costs (which are paid out of our own pocket at the moment), but strangely no one seems excited to pay for it ;-) If you are, I'm sure we can get in contact.

We do [have an issue](./101) to investigate using something that would take recent popular crates into account. If Rayon would occur in that list, one way of seeing it appear on the playground would be to contribute the effort needed to add that to crates.io.

As a specific point, the playground runs on a single core (again, because we are playing out of pocket), so you'd never get to see the benefits of Rayon in runtime.

I'm going to close this as a duplicate of #101, as that seems like the most likely path that Rayon would occur, but thank you for your suggestion!

**Closed by shepmaster** 2017-03-14 02:26 UTC
