### ISSUE TITLE
Please add full dark theme mode

### ISSUE THREAD

**Issue by artemismars** [integer32llc/rust-playground#759] opened 2021-12-19 15:53 UTC
I can see that playground supports the various code editor themes and it's amazing.
and I thought if playground webpage could support the full dark mode itself. It would be better.
because the background white part is quite annoying when I want to use dark code editor.
thanks! :)

**Comment by shepmaster** [comment] 2021-12-19 19:50
Duplicate of #544

**Closed by shepmaster** 2021-12-19 19:50 UTC
Labels: wontfix
