### ISSUE TITLE
Example RPN code fails to run

### ISSUE THREAD

**Issue by memco** [integer32llc/rust-playground#595] opened 2020-04-22 20:03 UTC
Hi, totally new to Rust and I clicked the playground link from the Rust homepage then clicked the run button and I see this:

```
Compiling playground v0.0.1 (/playground)
error: Could not apply operator `*` to the current stack: [2 + 3]
  --> src/main.rs:7:9
   |
7  |         compile_error!(concat!("Could not apply operator `", stringify!($op), "` to the current stack: ", stringify!($stack)))
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
44 |     println!("{}", rpn!(2 3 + *));
   |                    ------------- in this macro invocation
   |
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to previous error

error: could not compile `playground`.

To learn more, run the command again with --verbose.
```

Is it supposed to be broken? If so, what should I be looking for in order to see it run?

**Comment by shepmaster** [comment] 2020-04-22 20:14
> I clicked the playground link from the Rust homepage then clicked the run button

The link to the playground on https://www.rust-lang.org/ (I assume you mean this one:)

![image](https://user-images.githubusercontent.com/174509/80028936-f903a700-84b3-11ea-8736-148fb0fa984e.png)

Does not supply any code:

![image](https://user-images.githubusercontent.com/174509/80029005-16d10c00-84b4-11ea-9479-e17ecbce8834.png)

The default code of the playground is a basic hello world:

https://github.com/integer32llc/rust-playground/blob/77ce403cd0d4d2da0d4d424e841ce30623e3a209/ui/frontend/reducers/code.ts#L3-L5

It sounds like you visited the playground previously with that RPN code. Your last code is persisted in your local browser storage. Perhaps I should add a timestamp check and offer to reset things if someone hasn't visited the playground in sufficiently long.

**Comment by memco** [comment] 2020-04-30 04:42
Thanks for the explanation, I can see how the local storage feature is useful if you're using the playground as a scratch pad. I probably won't be visiting the scratch pad much for that kind of thing, but maybe the reset idea could be helpful for others like me who visited out of curiosity sometime in the past and have since forgotten they ever visited.

**Comment by shepmaster** [comment] 2020-05-06 01:31
Duplicate of #323

**Closed by shepmaster** 2020-05-06 01:31 UTC
