### ISSUE TITLE
Timeout for running, building, linting any code

### ISSUE THREAD

**Issue by bjorn3** [integer32llc/rust-playground#469] opened 2019-03-10 11:40 UTC
Eg:

```rust
fn main() { /*abc*/ }
```

```
   Compiling rand_os v0.1.2
   Compiling iovec v0.1.2
   Compiling num_cpus v1.10.0
   Compiling net2 v0.2.33
   Compiling memchr v2.2.0
   Compiling time v0.1.42
   Compiling rand v0.4.6
   Compiling xattr v0.2.2
   Compiling filetime v0.2.4
   Compiling atty v0.2.11
   Compiling termion v1.5.1
   Compiling MacTypes-sys v2.1.0
   Compiling memmap v0.7.0
   Compiling thread-id v3.3.0
   Compiling crossbeam-epoch v0.7.1
   Compiling crossbeam-epoch v0.3.1
   Compiling quote v0.6.11
   Compiling deflate v0.7.19
/root/entrypoint.sh: line 8:     7 Killed                  timeout --signal=KILL ${timeout} "$@"
```

**Comment by shepmaster** [comment] 2019-03-10 18:26
Unsure of the root cause, although https://github.com/rust-lang/cargo/pull/6720/files looks like a likely candidate.

**Comment by ehuss** [comment] 2019-03-10 18:27
Yea, I think I have a fix.  Testing with docker is a little slow.

**Comment by shepmaster** [comment] 2019-03-10 18:33
> Yea, I think I have a fix. Testing with docker is a little slow.

That can be an understatement. I tend to do some heavy editing of https://github.com/integer32llc/rust-playground/blob/master/compiler/base/Cargo.toml to reduce the number of crates that are required. It also looks like the intra-stage caching is broken again, at least on Travis, so that's probably not helping either.

**Comment by moxian** [comment] 2019-03-13 11:46
I see #6734 has been merged, but the nightly playground is still timing out.
Is there another issue in play here?

**Comment by shepmaster** [comment] 2019-03-13 13:26
> I see #6734 has been merged,

There are multiple steps:

1. The fix has to be merged into the Cargo codebase (that was https://github.com/rust-lang/cargo/pull/6734)
1. The Cargo update needs to be merged into Rust (this is https://github.com/rust-lang/rust/pull/59143)
1. Rust needs to be released (should be the next night, assuming nothing prevents the build from succeeding)

**Comment by shepmaster** [comment] 2019-03-15 01:59
Thank you, @ehuss!

**Closed by shepmaster** 2019-03-15 01:59 UTC
Labels: bug, upstream
