### ISSUE TITLE
Clippy Timing Out

### ISSUE THREAD

**Issue by JoshuaHall** [integer32llc/rust-playground#471] opened 2019-03-12 19:33 UTC
When I have run Clippy in the playground, it is timing out. It seems that it hasn't pre-checked any of the crates added by default so it is doing that and timing itself out. It's worked in the past for me so maybe something recently changed to cause this?

I tested this on the playground I was tinkering around in and then went to a new one in an incognito browser and had the same issue.

My output from Clippy:
```  Checking rand_os v0.1.2
    Checking iovec v0.1.2
    Checking num_cpus v1.10.0
    Checking net2 v0.2.33
    Checking time v0.1.42
    Checking memchr v2.2.0
    Checking rand v0.4.6
    Checking atty v0.2.11
    Checking filetime v0.2.4
    Checking xattr v0.2.2
    Checking thread-id v3.3.0
    Checking memmap v0.7.0
    Checking MacTypes-sys v2.1.0
    Checking termion v1.5.1
    Checking crossbeam-epoch v0.7.1
    Checking crossbeam-epoch v0.3.1
    Checking deflate v0.7.19
    Checking base64 v0.10.1
/root/entrypoint.sh: line 8:     7 Killed                  timeout --signal=KILL ${timeout} "$@"

**Comment by shepmaster** [comment] 2019-03-12 19:48
Duplicate of #469

**Closed by shepmaster** 2019-03-12 19:48 UTC

**Comment by JoshuaHall** [comment] 2019-03-12 19:50
I don't know how I didn't see that, my bad 😃
