### ISSUE TITLE
Automatically change from "Run" to "Build" when `fn main` is removed.

### ISSUE THREAD

**Issue by RalfJung** [integer32llc/rust-playground#377] opened 2018-08-08 15:27 UTC
Often I just want to build code, not run it. Sometimes having the main function there is a little annoying. I know I can add `#![crate_type="lib"]`, but try typing that fast (on a German keyboard, for extra challenge)... it's quite a mouthful.

Do you think it would make sense to switch to lib mode when I just remove the main function? The check could be something simple, like testing for the regex `fn +main`.

**Comment by shepmaster** [comment] 2018-08-08 16:44
Duplicate of #169 or #201

**Comment by shepmaster** [comment] 2018-08-08 16:45
My current gut feeling is to just add a "build" option in the dropdown, coupled with #368

**Closed by shepmaster** 2018-08-08 16:44 UTC
