### ISSUE TITLE
Rendering of ampersand character is broken

### ISSUE THREAD

**Issue by AnthonyMikh** [integer32llc/rust-playground#585] opened 2020-03-19 12:14 UTC
A picture is worth a thousand words.
Firefox (74.0):
![weird_ampersand](https://user-images.githubusercontent.com/19252795/77062874-c31f5e80-69ed-11ea-817a-2b9ea409c786.png)
Chrome (80.0.3987.149):
![weird_ampersand_chrome](https://user-images.githubusercontent.com/19252795/77063565-f6aeb880-69ee-11ea-9414-908d570beb7b.png)
(Yes, these glitchy characters are ampersands)
OS (although I don't think it is relevant): Windows 8.1

**Comment by shepmaster** [comment] 2020-03-19 12:47
Perhaps a duplicate of https://github.com/integer32llc/rust-playground/issues/112

**Comment by AnthonyMikh** [comment] 2020-03-19 14:23
Indeed, it was a local issue. Updating Source Code Pro fonts on my machine solved this.

**Closed** 2020-03-19 14:23 UTC
