### ISSUE TITLE
Feature request: Add a `Check` option

### ISSUE THREAD

**Issue by Centril** [integer32llc/rust-playground#522] opened 2019-07-30 21:56 UTC
It would be nice if there was a "Check" button to complement "Run", "Build", and "Test".
This would have been useful when minimizing the bug https://github.com/rust-lang/rust/issues/63150.

**Comment by shepmaster** [comment] 2019-08-05 15:23
Duplicate of #131

**Closed by shepmaster** 2019-08-05 15:23 UTC
