### ISSUE TITLE
Please add Auto complete feature ,like VSCode + Rust extension.

### ISSUE THREAD

**Issue by netroby** [integer32llc/rust-playground#705] opened 2021-04-15 01:47 UTC
Hello, would you please add auto complete feature, like we coding with VSCode + Rust extension.

That would be help if we want really quick and test the feature about Rust.

We only need a browser, and visit https://play.rust-lang.org

Then it works, we need auto complete, to reminder us how to use rust library, functions.

**Comment by shepmaster** [comment] 2021-04-15 01:54
Duplicate of #357

**Closed by shepmaster** 2021-04-15 01:54 UTC
Labels: wontfix
