### ISSUE TITLE
Cannot access with gist

### ISSUE THREAD

**Issue by CYBAI** [integer32llc/rust-playground#205] opened 2017-08-28 02:29 UTC
I was trying to access `rust-playground` with `gist`; however, it's stuck in loading.
Then, I open devtools to check; there's an error.

The URL with gist: https://play.rust-lang.org/?gist=9ccf40fae2347519fcae7dd42ddf5ed6
Error in console:
![image](https://user-images.githubusercontent.com/6782666/29757073-b485fdd6-8bdb-11e7-83a9-f16824eb3bd4.png)

**Comment by shepmaster** [comment] 2017-08-28 12:38
Duplicate of #135.

The gist you are using wasn't created by the playground, so it isn't found. The linked issue is for changing that logic to use some file if it's found.

**Closed by shepmaster** 2017-08-28 12:38 UTC

**Comment by CYBAI** [comment] 2017-08-28 15:12
Oh, sorry, I had checked the issues but didn't notice that one related to this issue...
Thanks for your reply!
