### ISSUE TITLE
Copy (Ctrl+C) doesn't work

### ISSUE THREAD

**Issue by dhardy** [integer32llc/rust-playground#227] opened 2017-11-02 11:03 UTC
It never has for me (though I some other editor bugs have been fixed; play is a lot more usable than it was originally).

E.g. if I select some text and press Ctrl+C (or right-click, copy), my clipboard is filled with ``.

Paste (with text from another source) does work. Copy+Paste does nothing (presumably bad clipboard contents ignored).

Using Firefox 55.0.3 on Fedora 25.

**Comment by shepmaster** [comment] 2017-11-02 12:16
Can you try the debugging steps listed in #96 and check the linked Ace issue to see if it seems relevant?

**Comment by dhardy** [comment] 2017-11-02 12:28
Same as in #96. I guess it's a duplicate then, sorry, but I think you were premature in closing, because it's still an issue.

**Comment by shepmaster** [comment] 2017-11-02 12:31
Duplicate of #96

**Closed by shepmaster** 2017-11-02 12:31 UTC

**Comment by shepmaster** [comment] 2017-11-02 12:32
I closed it because the reporter stopped caring about it. I've reopened it because you care about it. Either you will identify the root cause of the issue or stop caring about it as well, and then I'll close it again 😈

**Comment by vks** [comment] 2017-11-02 12:55
I'm not sure what you mean. I still care about it. What do you expect me to do? It seems to be the bug in Ace you linked, so my plan was to wait until it is fixed upstream. (I guess I don't care enough to invest the time to fix it myself. Especially since the simple editor works.)
