### ISSUE TITLE
add tokio-core & futures support

### ISSUE THREAD

**Issue by tekjar** [integer32llc/rust-playground#137] opened 2017-04-30 19:39 UTC
Hi @carols10cents, @shepmaster.  futures are one of the most wanted features in rust for people who want to write high perf n/w code. But people has issues understanding them properly (including me). Do you think it's a good idea to add support for `futures` & `tokio-core` in the playground so that people can quickly try something?

This will also be helpful for people who want to write tutorials/blogs or rustlings like crate for tokio. maybe I'll be able to explain with this sort of code

```rust
extern crate futures;
extern crate tokio_core;

use futures::future::*;
use tokio_core::reactor::Core;

fn main() {
    let mut reactor = Core::new().unwrap();
    let f1 = ok::<i32, i32>(1);

    // NOTES: 
    // 1. and_then executes the closures only when future is successful
    // 2. closure should return an IntoFuture (Result implements it) whose error is same as that of f1's 
    let f = f1.and_then(|v| {
        println!("{:?}", v);
        
        // Ok::<(), f32>(()) // doesn't work (2)
        // Ok::<i32, i32>(100)  // works (2)
        // Ok(()) // works (2)
        Ok(100) // works (2)
    });

    assert_eq!(Ok(100), reactor.run(f));

    let f2 = err::<i32, i32>(-1);

    let f = f2.and_then(|v| {
        println!("{:?}", v); // doesn't get executed
        Ok(())
    });

    assert_eq!(Err(-1), reactor.run(f));
}
```

**Comment by shepmaster** [comment] 2017-04-30 20:32
Duplicate of #133, duplicate of #101.

**Closed by shepmaster** 2017-04-30 20:32 UTC
