### ISSUE TITLE
Cannot activate iOS paste in the editor window 

### ISSUE THREAD

**Issue by EdmundsEcho** [integer32llc/rust-playground#574] opened 2020-02-04 00:27 UTC
The online playground is a wonderful resource. I just realized that I cannot paste code into the editor’s window using my iPhone.  The copy/paste dialog does not activate. 

 I have the latest iOS and tried to do so in chrome and the DuckDuckGo browser. Neither worked.

**Comment by shepmaster** [comment] 2020-02-11 14:59
Duplicate of #451

**Closed by shepmaster** 2020-02-11 14:59 UTC
Labels: upstream

**Comment by EdmundsEcho** [comment] 2020-02-11 16:00
I just tested the solution to use the *Style: simple* configuration in iOS chrome and DuckDuckGo. It works.  Thank you. \- E
