### ISSUE TITLE
Shall there be a rust-playground Docker image on Docker hub?

### ISSUE THREAD

**Issue by vi** [integer32llc/rust-playground#233] opened 2017-11-23 01:21 UTC
I see mentions of Docker in `.travis.yml`. But searching Docker Hub for `playground`, `rust`, `integer32` doesn't bring anything of interest.

Maybe there should be official easy-to-deploy images for rust-playground? Just start it and point browser to 127.0.0.1:1234 and start playing. Sandbox and things are handled inside automatically.

The list of included crates should be easily configurable parameter (not requiring container rebuild). Ideally private registries should be supported too.

**Comment by shepmaster** [comment] 2017-11-23 03:27
The primary playground containers are at https://hub.docker.com/r/shepmaster/rust-stable/ (and -beta, -nightly, rustfmt, clippy, etc.) 

Duplicate of #58

**Comment by shepmaster** [comment] 2017-11-23 03:28
See also #191

**Closed by shepmaster** 2017-11-23 03:27 UTC

**Comment by shepmaster** [comment] 2017-11-23 03:29
> The list of included crates should be easily configurable parameter (not requiring container rebuild).

Not possible with the current architecture of the Playground.
