### ISSUE TITLE
Rust Playground doesn't wait for user input

### ISSUE THREAD

**Issue by aiexplorations** [integer32llc/rust-playground#610] opened 2020-06-22 11:01 UTC
Hello Rust team,

I'm very new to Rust, and hope to learn more about the language in the coming weeks and months. 

I was trying out some very basic code on the Rust Playground which unfortunately didn't work as expected. Could you please help?

This is a variation on "Programming a Guessing Game" from the Rust Book.

`use std::io;

fn main() {
    println!("Hello, Rajesh!");
    
    println!("Please input a number:");
    
    let mut number = String::new();
    
    io::stdin()
        .read_line(&mut number)
        .expect("Failed to read line");
    
    println!("Number is {}", number);
    
}`

![image](https://user-images.githubusercontent.com/10044506/85280427-bfe0b680-b4a5-11ea-9e91-e82ca5d33301.png)

**Comment by shepmaster** [comment] 2020-06-22 12:47
Duplicate of #22

**Closed by shepmaster** 2020-06-22 12:47 UTC

**Comment by shepmaster** [comment] 2020-06-22 12:49
Unfortunately, adding support for streaming stdin (as you'd want with the guessing game) is very non-trivial, and probably would require some interesting architecture changes to have a long(er) running process on the server.

**Comment by aiexplorations** [comment] 2020-06-22 17:32
@shepmaster Thanks for clarifying the reason for this. In any case I set up a rustlang environment on my machine and it works okay.
