### ISSUE TITLE
layout problem on config

### ISSUE THREAD

**Issue by mone27** [integer32llc/rust-playground#222] opened 2017-10-30 10:04 UTC
When you open the config  menu there are some layout problem: the "done" button is placed over a menu and the last entry on the menu is outside the white box.
![screenshot from 2017-10-30 10-45-59](https://user-images.githubusercontent.com/17617810/32164908-2acb94ea-bd61-11e7-80ac-5f51f5731be3.png)
I have Ubuntu 17.10 and the bug is present on Firefox Nightly 58.0a, Firefox 56.0, Chromium 62 as well as Epiphany 3.26.1.(all the browser I have tested)
On the other hand on mobile(android 8.0) the bug isn't present neither on Firefox Nightly nor Chrome.
I hope this report would be useful.
I'm willing to help fixing it if I can understand better where it is

**Comment by shepmaster** [comment] 2017-10-30 12:52
Very strange! I'm on macOS 10.12.6 and don't see that:

**Firefox 56.0**

![image](https://user-images.githubusercontent.com/174509/32171683-6714f5e8-bd4f-11e7-8569-03390568bffd.png)

**Chrome canary 64.0.3253.0**

![image](https://user-images.githubusercontent.com/174509/32171718-82c249e4-bd4f-11e7-9577-ee71d332dc44.png)

**Safari 11.0 (12604.1.38.1.7)**

![image](https://user-images.githubusercontent.com/174509/32171758-9fca3d8a-bd4f-11e7-80dd-40a343a8fa97.png)

**Comment by shepmaster** [comment] 2017-10-30 13:00
You may need to do more investigation to narrow down the root cause — isn't CSS fun! Otherwise, I'll need to wrangle up a Ubuntu VM, which will probably take a while.

**Comment by mone27** [comment] 2017-10-30 15:42
I've  tested it on other platforms and it seems a Linux issue.
It works on windows (both Firefox 56 and edge)
I tested it on Ubuntu 16.04 lts (Firefox 56) and on kali Linux (Firefox esr 52) and it doesn't work on any of those systems. 
It remains to test it under KDE because could be gtk issue. 
I'll dive into CSS during next days

**Comment by hcpl** [comment] 2017-10-30 17:59
Can confirm this under Ubuntu 14.04 (i3wm, Firefox 56):

![2017-10-30-195525-646x258_maim_slop](https://user-images.githubusercontent.com/17436405/32187031-711d51cc-bdac-11e7-88c0-60f1f49c5180.png)

**Comment by shepmaster** [comment] 2018-04-20 20:39
This is "fixed by accident" by... deleting the config modal! :-) /cc #299

**Closed by shepmaster** 2018-04-20 20:39 UTC

**Comment by mone27** [comment] 2018-04-21 06:14
Nice to ear this, as you have seen I hadn't had the time to try to fix it so I really like this solution :P
